name: 📅 Actualizar datos GLP

# Dar permiso de escritura al GITHUB_TOKEN para poder hacer push
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'                # diario a medianoche UTC
  workflow_dispatch:

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Instalar dependencias
        run: pip install --no-cache-dir -r requirements.txt

      - name: Generar archivos GeoJSON
        run: python main.py

      - name: Commit y push de los cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/gasolineras-glp.geojson
          git diff --staged --quiet || git commit -m "🔄 Actualización diaria de datos GLP"
          git push || echo "Sin cambios para pushear"
