name: 📅 Actualizar datos GLP

on:
  # Ejecutar cada día a las 00:00 UTC (ajusta cron si necesitas hora local)
  schedule:
    - cron: '0 0 * * *'                # diario a medianoche UTC :contentReference[oaicite:2]{index=2}
  # Permite disparar manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0               # necesario para push :contentReference[oaicite:3]{index=3}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Instalar dependencias
        run: pip install --no-cache-dir -r requirements.txt

      - name: Generar archivos GeoJSON
        run: python main.py

      - name: Commit y push de los cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/gasolineras-glp.geojson
          # Solo commitear si hay cambios
          git diff --staged --quiet || git commit -m "🔄 Actualización diaria de datos GLP"
          # Push y, si no hay nada que push, no fallar
          git push || echo "Sin cambios para pushear"
